version: '3.9'
services:
  igniteLabNodeJS:
    image: postgres
    container_name: igniteLabNodeJS
    ports:
      - "5432:5432"
    volumes:
      - "igniteLabNodeJS:/data/postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lab

volumes:
  igniteLabNodeJS:
